# Generated by Django 4.2.2 on 2023-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(max_length=30)),
                ('face_done', models.CharField(default='no', max_length=10, null=True)),
                ('text_done', models.CharField(default='no', max_length=10, null=True)),
            ],
        ),
    ]
